version: "3.9"

services:
  db:
    image: postgres:14.19-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_DB: aiworkflow
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app_user:app_password@db:5432/aiworkflow
      STREAMLIT_SERVER_HEADLESS: "true"
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
